# Build config
markdown: kramdown
highlighter: rouge

# Array of files/directories to exclude from the conversion
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .ruby-version

# Array of files/directories to include that would otherwise be excluded by Jekyll (e.g. dotfiles)
include:
  - .well-known

excerpt_separator: "<!-- more -->"

# Permalinks
permalink: /notes/:title

# YAML frontmatter defaults
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Setup
url: https://dideler.github.io
title: Dennis Ideler
tagline: Life's a beach
description: An islander obsessed with how we build software and continuous improvement
commentsystem:
disqus:	example
branch: master

author:
  name: Dennis Ideler
  url: https://twitter.com/dideler
  email: ideler.dennis@gmail.com

plugins:
  - jekyll-sitemap

# icon: /assets/images/icon.png  # Icon appears in centre of cover. 512x512 works well.
cover: /assets/images/palm-trees.jpg

social:
  - icon:	twitter
    url:  https://twitter.com/dideler
    desc:	Follow me on Twitter

  - icon:	github
    url:  https://github.com/dideler
    desc:	Follow me on GitHub

  - icon:	linkedin
    url:  http://www.linkedin.com/in/dennisideler
    desc:	Connect on LinkedIn

  - icon:	feed
    url:  https://dideler.github.io/atom.xml
    desc:	Subscribe to my RSS feed

menu:
  - title: Home
    url: /

  - title: About
    url: /about

copyright:
  owner:

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
