# Build config
markdown:	kramdown
highlighter: pygments

# Array of files/directories to exclude from the conversion
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink: /posts/:title

# Setup
url: http://dennisideler.com
title: Dennis Ideler
tagline:
description: Admirer of open-source software, simplicity, usability, good documentation, and practice over theory.
commentsystem:
disqus:	example
paginate:	5
branch: master

author:
  name: Dennis Ideler
  url: https://twitter.com/dideler
  email: ideler.dennis@gmail.com

gems:
  - jekyll-sitemap

# icon: /assets/images/icon.png  # Icon appears in centre of cover. 512x512 works well.
cover: /assets/images/palm-trees.jpg

social:
  - icon:	twitter
    url:  https://twitter.com/dideler
    desc:	Follow me on Twitter

  - icon:	github
    url:  https://github.com/dideler
    desc:	Follow me on GitHub

  - icon:	linkedin
    url:  http://www.linkedin.com/in/dennisideler
    desc:	Connect on LinkedIn

  - icon:	feed
    url:  http://dennisideler.com/atom.xml
    desc:	Subscribe to my RSS feed

menu:
  - title: Home
    url: /

  - title: About
    url: /about

copyright:
  owner:

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
