# Dependencies
markdown:	kramdown
highlighter: pygments

# Permalinks
permalink: /posts/:title

# Setup
url: http://dennisideler.com
title: “There is no real difference between work and play – it's all living.”
tagline: Some tagline
description: Some description
commentsystem: google
disqus:	example
paginate:	5

author:
  name: Dennis Ideler
  url: https://twitter.com/dideler
  email: ideler.dennis@gmail.com

gems:
  - jekyll-sitemap

# Custom vars
handle: dideler
icon: /assets/images/icon.png
cover: /assets/images/cover.jpg

social:
  - icon:	twitter
    url:  https://twitter.com/dideler
    desc:	Follow me on twitter

  - icon:	github
    url:  https://github.com/dideler
    desc:	Follow me on github

  - icon:	googleplus-alt
    url:  https://plus.google.com/+DennisIdeler/about
    desc:	Follow me on google+

  - icon:	feed
    url:  http://dennisideler.com/atom.xml
    desc:	Subscribe to my feed

menu:
  - title: Home
    url: /

  - title: About
    url: /about

copyright:
  owner:

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
